"""128 client records matching the frontend mocks."""


def _orig(id_, fn, ln, email, phone, city, num, status, agent_id, past, accept, manual, rejected, last90, flags, summary):
    return {
        "id": id_, "user_id": f"user_{id_:03d}",
        "first_name": fn, "last_name": ln, "email": email,
        "phone": phone, "city": city, "client_number": num, "status": status,
        "photo_url": f"https://i.pravatar.cc/300?u=client-{id_}",
        "agent_id": agent_id,
        "past_claim_count": past, "accept_claim": accept,
        "manual_review_claim": manual, "rejected_claim": rejected,
        "last_90_days_claim_count": last90,
        "history_flags": flags, "history_summary": summary,
    }


def _new(id_, fn, ln, city, agent_id, status="active"):
    safe_fn = fn.lower().replace("í", "i").replace("á", "a").replace("é", "e").replace("ó", "o").replace("ú", "u").replace("ñ", "n")
    safe_ln = ln.lower().replace("í", "i").replace("á", "a").replace("é", "e").replace("ó", "o").replace("ú", "u").replace("ñ", "n")
    return {
        "id": id_, "user_id": f"user_{id_:03d}",
        "first_name": fn, "last_name": ln,
        "email": f"{safe_fn}.{safe_ln}@zipshield.io",
        "phone": None, "city": city, "client_number": f"CL-{id_:03d}",
        "status": status, "photo_url": f"https://i.pravatar.cc/300?u=client-{id_}",
        "agent_id": agent_id,
        "past_claim_count": 0, "accept_claim": 0, "manual_review_claim": 0,
        "rejected_claim": 0, "last_90_days_claim_count": 0,
        "history_flags": [], "history_summary": "Nuevo cliente sin reclamos previos",
    }


# Original 47 with history
CLIENTS = [
    _orig(1, "Lucas", "García", "lucas.garcia@zipshield.io", "+54 11 5421-1001", "Buenos Aires", "CL-001", "active", 1, 2, 2, 0, 0, 1, [], "Low-risk user with prior accepted car damage claims"),
    _orig(2, "Sofía", "Martínez", "sofia.martinez@zipshield.io", "+54 351 421-1002", "Córdoba", "CL-002", "active", 2, 4, 3, 1, 0, 2, [], "Mostly accepted vehicle claims with one manual review"),
    _orig(3, "Mateo", "Rodríguez", "mateo.rodriguez@zipshield.io", None, "Rosario", "CL-003", "active", 1, 1, 1, 0, 0, 0, [], "Limited history and no notable risk"),
    _orig(4, "Camila", "López", "camila.lopez@zipshield.io", "+54 261 421-1004", "Mendoza", "CL-004", "active", 4, 6, 4, 1, 1, 2, [], "Moderate history with mostly accepted claims"),
    _orig(5, "Diego", "González", "diego.gonzalez@zipshield.io", "+54 381 421-1005", "Tucumán", "CL-005", "inactive", 5, 7, 2, 2, 3, 4, ["user_history_risk"], "Several exaggerated vehicle damage claims in recent history"),
    _orig(6, "Isabella", "Pérez", "isabella.perez@zipshield.io", None, "La Plata", "CL-006", "active", 6, 0, 0, 0, 0, 0, [], "New user with no prior claim history"),
    _orig(7, "Sebastián", "Sánchez", "sebastian.sanchez@zipshield.io", "+54 223 421-1007", "Mar del Plata", "CL-007", "active", 7, 3, 2, 1, 0, 1, [], "Prior claims were mostly supported"),
    _orig(8, "Valentina", "Ramírez", "valentina.ramirez@zipshield.io", "+54 387 421-1008", "Salta", "CL-008", "active", 8, 5, 2, 2, 1, 3, ["user_history_risk"], "Several prior claims required image-quality review"),
    _orig(9, "Andrés", "Torres", "andres.torres@zipshield.io", None, "Bahía Blanca", "CL-009", "active", 9, 1, 1, 0, 0, 1, [], "Low-risk laptop claim history"),
    _orig(10, "Lucía", "Flores", "lucia.flores@zipshield.io", "+54 299 421-1010", "Neuquén", "CL-010", "active", 10, 2, 2, 0, 0, 1, [], "Prior hinge claim accepted with clear evidence"),
    _orig(11, "Joaquín", "Rivera", "joaquin.rivera@zipshield.io", "+54 342 421-1011", "Santa Fe", "CL-011", "active", 1, 4, 3, 1, 0, 2, [], "Mostly accepted electronics damage history"),
    _orig(12, "Martina", "Gómez", "martina.gomez@zipshield.io", "+54 264 421-1012", "San Juan", "CL-012", "active", 12, 3, 2, 0, 1, 1, [], "One rejected laptop cosmetic claim"),
    _orig(13, "Tomás", "Díaz", "tomas.diaz@zipshield.io", "+54 11 5421-1013", "Buenos Aires", "CL-013", "active", 1, 8, 3, 2, 3, 5, ["user_history_risk", "manual_review_required"], "Previously submitted a visually similar fender damage image"),
    _orig(14, "Emma", "Reyes", "emma.reyes@zipshield.io", None, "Córdoba", "CL-014", "active", 2, 2, 1, 1, 0, 1, ["user_history_risk"], "Prior windshield claim needed manual review"),
    _orig(15, "Bruno", "Cruz", "bruno.cruz@zipshield.io", "+54 341 421-1015", "Rosario", "CL-015", "active", 4, 1, 1, 0, 0, 0, [], "Low-risk package claim history"),
    _orig(16, "Catalina", "Morales", "catalina.morales@zipshield.io", "+54 261 421-1016", "Mendoza", "CL-016", "inactive", 4, 11, 2, 2, 7, 6, ["user_history_risk", "manual_review_required"], "Frequent rejected car scratch claims"),
    _orig(17, "Felipe", "Ortiz", "felipe.ortiz@zipshield.io", None, "Tucumán", "CL-017", "active", 5, 2, 2, 0, 0, 1, [], "Low-risk laptop damage claimant"),
    _orig(18, "Antonella", "Gutiérrez", "antonella.gutierrez@zipshield.io", "+54 221 421-1018", "La Plata", "CL-018", "active", 6, 5, 4, 0, 1, 2, [], "Mostly accepted claims with one contradiction"),
    _orig(19, "Nicolás", "Castro", "nicolas.castro@zipshield.io", "+54 223 421-1019", "Mar del Plata", "CL-019", "active", 7, 3, 2, 1, 0, 1, [], "Prior laptop claims were plausible"),
    _orig(20, "Renata", "Jiménez", "renata.jimenez@zipshield.io", None, "Salta", "CL-020", "active", 8, 1, 0, 1, 0, 1, ["user_history_risk"], "Limited history but prior claim needed manual review"),
    _orig(21, "Federico", "Mendoza", "federico.mendoza@zipshield.io", "+54 291 421-1021", "Bahía Blanca", "CL-021", "active", 9, 6, 4, 1, 1, 3, [], "Mostly accepted cosmetic laptop claims"),
    _orig(22, "Julieta", "Vargas", "julieta.vargas@zipshield.io", "+54 299 421-1022", "Neuquén", "CL-022", "active", 10, 4, 2, 1, 1, 2, [], "Mixed laptop screen damage history"),
    _orig(23, "Augusto", "Romero", "augusto.romero@zipshield.io", None, "Santa Fe", "CL-023", "active", 4, 0, 0, 0, 0, 0, [], "New user with no prior claim history"),
    _orig(24, "Florencia", "Herrera", "florencia.herrera@zipshield.io", "+54 264 421-1024", "San Juan", "CL-024", "active", 12, 7, 2, 3, 2, 4, ["user_history_risk", "manual_review_required"], "Repeated laptop lid damage claims with review history"),
    _orig(25, "Hernán", "Medina", "hernan.medina@zipshield.io", "+54 11 5421-1025", "Buenos Aires", "CL-025", "active", 1, 2, 2, 0, 0, 1, [], "Low-risk missing key claim history"),
    _orig(26, "Paula", "Castillo", "paula.castillo@zipshield.io", "+54 351 421-1026", "Córdoba", "CL-026", "active", 2, 5, 2, 1, 2, 2, ["user_history_risk"], "Prior claims sometimes confused tablet and laptop evidence"),
    _orig(27, "Ramiro", "Ruiz", "ramiro.ruiz@zipshield.io", None, "Rosario", "CL-027", "active", 5, 3, 1, 2, 0, 2, ["user_history_risk"], "Prior images had glare and reflection ambiguity"),
    _orig(28, "Victoria", "Aguilar", "victoria.aguilar@zipshield.io", "+54 261 421-1028", "Mendoza", "CL-028", "active", 4, 9, 4, 3, 2, 5, ["user_history_risk", "manual_review_required"], "Repeated hinge damage claims across multiple months"),
    _orig(29, "Esteban", "Vega", "esteban.vega@zipshield.io", "+54 381 421-1029", "Tucumán", "CL-029", "active", 5, 2, 2, 0, 0, 1, [], "Low-risk package damage history"),
    _orig(30, "Macarena", "Rojas", "macarena.rojas@zipshield.io", None, "La Plata", "CL-030", "active", 6, 4, 3, 0, 1, 2, [], "Mostly accepted package claims"),
    _orig(31, "Lautaro", "Acosta", "lautaro.acosta@zipshield.io", "+54 223 421-1031", "Mar del Plata", "CL-031", "active", 7, 6, 3, 2, 1, 3, ["user_history_risk"], "Prior package claims often needed evidence review"),
    _orig(32, "Belén", "Cabrera", "belen.cabrera@zipshield.io", "+54 387 421-1032", "Salta", "CL-032", "active", 8, 1, 0, 1, 0, 1, ["manual_review_required"], "Prior missing item claim lacked enough evidence"),
    _orig(33, "Maximiliano", "Núñez", "maximiliano.nunez@zipshield.io", None, "Bahía Blanca", "CL-033", "active", 9, 5, 2, 1, 2, 3, ["user_history_risk"], "Several package severity exaggeration claims"),
    _orig(34, "Constanza", "Cárdenas", "constanza.cardenas@zipshield.io", "+54 299 421-1034", "Neuquén", "CL-034", "active", 10, 2, 1, 1, 0, 1, ["user_history_risk"], "Prior label damage image was unreadable"),
    _orig(35, "Gonzalo", "Salazar", "gonzalo.salazar@zipshield.io", "+54 342 421-1035", "Santa Fe", "CL-035", "active", 9, 0, 0, 0, 0, 0, [], "New user with no prior claim history"),
    _orig(36, "Daniela", "Esquivel", "daniela.esquivel@zipshield.io", None, "San Juan", "CL-036", "active", 12, 4, 2, 2, 0, 3, ["user_history_risk"], "Prior water damage claims needed review for authenticity"),
    _orig(37, "Joel", "Paz", "joel.paz@zipshield.io", "+54 11 5421-1037", "Buenos Aires", "CL-037", "inactive", 1, 14, 4, 4, 6, 9, ["user_history_risk", "manual_review_required"], "Unusually frequent package damage claims"),
    _orig(38, "Carolina", "Soto", "carolina.soto@zipshield.io", "+54 351 421-1038", "Córdoba", "CL-038", "active", 2, 3, 2, 0, 1, 1, [], "One prior broken item claim was contradicted"),
    _orig(39, "Alejo", "Iglesias", "alejo.iglesias@zipshield.io", None, "Rosario", "CL-039", "active", 9, 2, 1, 1, 0, 1, ["user_history_risk"], "Prior stain claim was ambiguous due to low light"),
    _orig(40, "Anabella", "Delgado", "anabella.delgado@zipshield.io", "+54 261 421-1040", "Mendoza", "CL-040", "active", 4, 8, 3, 2, 3, 5, ["user_history_risk", "manual_review_required"], "Prior open box image looked similar to current evidence pattern"),
    _orig(41, "Iñaki", "Ríos", "inaki.rios@zipshield.io", "+54 381 421-1041", "Tucumán", "CL-041", "active", 5, 3, 2, 0, 1, 1, ["manual_review_required"], "Prior car claims had mixed outcomes and should be reviewed carefully"),
    _orig(42, "Trinidad", "Méndez", "trinidad.mendez@zipshield.io", None, "La Plata", "CL-042", "active", 6, 5, 3, 1, 1, 2, ["manual_review_required"], "Prior vehicle claims include one rejection and one manual review"),
    _orig(43, "Octavio", "Quiroga", "octavio.quiroga@zipshield.io", "+54 223 421-1043", "Mar del Plata", "CL-043", "active", 7, 1, 0, 1, 0, 1, ["user_history_risk"], "Prior claim involved confusing toy object evidence"),
    _orig(44, "Bianca", "Espinosa", "bianca.espinosa@zipshield.io", "+54 387 421-1044", "Salta", "CL-044", "inactive", 8, 2, 0, 2, 0, 2, ["user_history_risk", "manual_review_required"], "Prior evidence included screenshots instead of original photos"),
    _orig(45, "Cristóbal", "Lagos", "cristobal.lagos@zipshield.io", None, "Bahía Blanca", "CL-045", "active", 9, 4, 2, 1, 1, 2, ["user_history_risk"], "Prior claim confused monitor or tablet damage with laptop damage"),
    _orig(46, "Antonia", "Bustos", "antonia.bustos@zipshield.io", "+54 299 421-1046", "Neuquén", "CL-046", "active", 10, 6, 3, 2, 1, 3, ["user_history_risk"], "Prior claims sometimes confused left and right side components"),
    _orig(47, "Lorenzo", "Vázquez", "lorenzo.vazquez@zipshield.io", "+54 342 421-1047", "Santa Fe", "CL-047", "active", 11, 7, 3, 1, 3, 4, ["user_history_risk", "manual_review_required"], "Repeated side-specific car claims with some rejected mismatches"),
]

# 81 new clients
_new_data = [
    # (firstName, lastName, city, agentId, status)
    (48, "Agustín", "Vidal", "Buenos Aires", 1, "active"),
    (49, "Beatriz", "Sosa", "Buenos Aires", 1, "active"),
    (50, "Cecilia", "Aguirre", "Buenos Aires", 1, "active"),
    (51, "Damián", "Benítez", "La Plata", 1, "inactive"),
    (52, "Eliana", "Castillo", "Buenos Aires", 1, "active"),
    (53, "Fabián", "Domínguez", "Mar del Plata", 1, "active"),
    (54, "Gabriela", "Echeverría", "Buenos Aires", 1, "active"),
    (55, "Horacio", "Ferreyra", "La Plata", 1, "active"),
    (56, "Inés", "Gallardo", "Córdoba", 2, "active"),
    (57, "Jorge", "Hernández", "Córdoba", 2, "active"),
    (58, "Karina", "Iglesias", "Córdoba", 2, "active"),
    (59, "Liam", "Juárez", "Río Cuarto", 2, "active"),
    (60, "Mariana", "Kessler", "Córdoba", 2, "inactive"),
    (61, "Nicolás", "López", "Mendoza", 4, "active"),
    (62, "Olivia", "Mancini", "Mendoza", 4, "active"),
    (63, "Pablo", "Naveiro", "Mendoza", 4, "active"),
    (64, "Rocío", "Ojeda", "San Rafael", 4, "active"),
    (65, "Santiago", "Peralta", "Mendoza", 4, "active"),
    (66, "Tatiana", "Quintana", "Mendoza", 4, "active"),
    (67, "Ulises", "Ríos", "Mendoza", 4, "active"),
    (68, "Valeria", "Salinas", "Mendoza", 4, "inactive"),
    (69, "Walter", "Tejada", "San Rafael", 4, "active"),
    (70, "Ximena", "Uría", "Mendoza", 4, "active"),
    (71, "Yamila", "Vázquez", "Mendoza", 4, "active"),
    (72, "Zoé", "Werner", "Mendoza", 4, "active"),
    (73, "Adrián", "Yacobi", "Mendoza", 4, "active"),
    (74, "Brenda", "Zambrano", "San Rafael", 4, "active"),
    (75, "Cristian", "Alarcón", "Mendoza", 4, "active"),
    (76, "Débora", "Bordón", "Mendoza", 4, "active"),
    (77, "Ezequiel", "Caracciolo", "Tucumán", 5, "active"),
    (78, "Fernanda", "Delgadillo", "Tucumán", 5, "active"),
    (79, "Gastón", "Escudero", "Tucumán", 5, "active"),
    (80, "Helena", "Fontana", "Tucumán", 5, "inactive"),
    (81, "Ignacio", "Guzmán", "Tucumán", 5, "active"),
    (82, "Jimena", "Hidalgo", "Tucumán", 5, "active"),
    (83, "Kevin", "Iturralde", "Salta", 5, "active"),
    (84, "Lorena", "Jaramillo", "Tucumán", 5, "active"),
    (85, "Manuel", "Krause", "Tucumán", 5, "active"),
    (86, "Noelia", "Larrañaga", "Salta", 5, "active"),
    (87, "Oscar", "Maldonado", "Tucumán", 5, "active"),
    (88, "Patricia", "Núñez", "Tucumán", 5, "active"),
    (89, "Quirino", "Oliveros", "Mar del Plata", 7, "active"),
    (90, "Raquel", "Páez", "Mar del Plata", 7, "active"),
    (91, "Susana", "Quiroga", "Mar del Plata", 7, "active"),
    (92, "Teresa", "Robles", "Bahía Blanca", 7, "active"),
    (93, "Vanesa", "Suárez", "Mar del Plata", 7, "active"),
    (94, "Wilson", "Tagliaferro", "Mar del Plata", 7, "inactive"),
    (95, "Xavier", "Urquijo", "Mar del Plata", 7, "active"),
    (96, "Yael", "Velasco", "Salta", 8, "active"),
    (97, "Zaira", "Wagner", "Bahía Blanca", 9, "active"),
    (98, "Alejandra", "Aguero", "Bahía Blanca", 9, "active"),
    (99, "Benjamín", "Borda", "Bahía Blanca", 9, "active"),
    (100, "Carla", "Cáceres", "Bahía Blanca", 9, "active"),
    (101, "Darío", "Domínguez", "Bahía Blanca", 9, "inactive"),
    (102, "Estela", "Egaña", "Comodoro Rivadavia", 9, "active"),
    (103, "Franco", "Farías", "Bahía Blanca", 9, "active"),
    (104, "Gisela", "Godoy", "Bahía Blanca", 9, "active"),
    (105, "Hernando", "Herrero", "Bahía Blanca", 9, "active"),
    (106, "Irene", "Insaurralde", "Bahía Blanca", 9, "active"),
    (107, "Julián", "Jurado", "Comodoro Rivadavia", 9, "active"),
    (108, "Kiara", "Kovacs", "Bahía Blanca", 9, "active"),
    (109, "Lautaro", "Larroca", "Bahía Blanca", 9, "inactive"),
    (110, "Marisol", "Molina", "Bahía Blanca", 9, "active"),
    (111, "Nahuel", "Nogueira", "Bahía Blanca", 9, "active"),
    (112, "Olga", "Ocampo", "Comodoro Rivadavia", 9, "active"),
    (113, "Pedro", "Palacios", "Bahía Blanca", 9, "active"),
    (114, "Rosa", "Ramallo", "Bahía Blanca", 9, "active"),
    (115, "Sebastián", "Salgado", "Bahía Blanca", 9, "active"),
    (116, "Tomasa", "Tabaré", "Neuquén", 10, "active"),
    (117, "Uriel", "Uribarri", "Neuquén", 10, "active"),
    (118, "Vicente", "Vergara", "Neuquén", 10, "active"),
    (119, "Yanina", "Yáñez", "Neuquén", 10, "inactive"),
    (120, "Amparo", "Acuña", "Neuquén", 10, "active"),
    (121, "Boris", "Brizuela", "Neuquén", 10, "active"),
    (122, "Carmen", "Calderón", "Neuquén", 10, "active"),
    (123, "Diana", "Damico", "Neuquén", 10, "active"),
    (124, "Elías", "Escalada", "San Juan", 12, "active"),
    (125, "Felisa", "Fonseca", "San Juan", 12, "active"),
    (126, "Gerardo", "Gauna", "San Juan", 12, "active"),
    (127, "Hilda", "Heredia", "San Juan", 12, "inactive"),
    (128, "Iván", "Inchausti", "San Juan", 12, "active"),
]

for tup in _new_data:
    CLIENTS.append(_new(*tup))
